# Generated by Django 4.1.7 on 2023-09-09 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denom', models.CharField(max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=50, unique=True)),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TerriVille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denom', models.CharField(max_length=70, unique=True)),
                ('prov', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.province')),
            ],
            options={
                'verbose_name': 'Ville ou Territoire',
                'verbose_name_plural': 'Villes ou Territoires',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denom', models.CharField(blank=True, max_length=70)),
                ('nom_bour', models.CharField(max_length=9)),
                ('TerriVi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.terriville')),
                ('prov', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
