# Generated by Django 4.2.5 on 2023-10-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actedesc',
            old_name='cod_qr',
            new_name='cod_qtr',
        ),
    ]
