# Generated by Django 4.1.7 on 2023-09-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='nom_bour',
            field=models.CharField(max_length=50),
        ),
    ]
