# Generated by Django 4.1.7 on 2023-09-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat_Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medecin_traitant', models.CharField(blank=True, max_length=120)),
                ('nom_defunt', models.CharField(blank=True, max_length=40)),
                ('post_nom_defunt', models.CharField(blank=True, max_length=40)),
                ('prenom_defunt', models.CharField(blank=True, max_length=40)),
                ('sexe_defunt', models.CharField(blank=True, choices=[('m', 'Masculin'), ('f', 'Feminin')], max_length=1)),
                ('hopital_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.hopital')),
            ],
            options={
                'verbose_name': 'Certificat de Décès',
                'verbose_name_plural': 'Certificats de Décès',
                'unique_together': {('nom_defunt', 'post_nom_defunt', 'prenom_defunt')},
            },
        ),
    ]
