# Generated by Django 4.1.7 on 2023-09-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_commune_nom_bour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatnaissance',
            name='sexe_enfant',
            field=models.CharField(blank=True, choices=[('m', 'Masculin'), ('f', 'Feminin')], max_length=1),
        ),
    ]
