# Generated by Django 4.1.7 on 2023-09-10 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_myuser_is_staff_myuser_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'verbose_name': 'Commune', 'verbose_name_plural': 'Communes'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denom', models.CharField(blank=True, max_length=70)),
                ('nom_bour', models.CharField(max_length=9)),
                ('TerriVi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.terriville')),
                ('prov', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hopital',
                'verbose_name_plural': 'Hopitals',
            },
        ),
    ]
