# Generated by Django 4.2.5 on 2023-09-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_certificat_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actenaiss',
            old_name='date_enregitrement',
            new_name='date_enregistrement',
        ),
    ]
