# Generated by Django 4.1.7 on 2023-09-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_myuser_date_joined_myuser_email_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopital',
            name='email',
            field=models.EmailField(default='rme', max_length=254),
            preserve_default=False,
        ),
    ]
