# Generated by Django 4.2.5 on 2023-10-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_date_enregitrement_actenaiss_date_enregistrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat_desc',
            name='cause_desc',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
