# Generated by Django 4.1.7 on 2023-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_commune_options_alter_myuser_options_hopital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopital',
            name='nom_bour',
        ),
        migrations.AddField(
            model_name='hopital',
            name='numeros_id',
            field=models.CharField(default=4, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
