# Generated by Django 4.1.7 on 2023-09-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_hopital_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254, unique=True),
        ),
    ]
