# Generated by Django 4.2.5 on 2023-10-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_cod_qtr_actedesc_cod_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actedesc',
            name='cod_qr',
            field=models.ImageField(blank=True, null=True, upload_to='acte_desc'),
        ),
    ]
