# Generated by Django 4.1.7 on 2023-09-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_certificatnaissance_sexe_enfant'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatnaissance',
            name='numero_cert',
            field=models.CharField(default=77, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificatnaissance',
            name='poid_enfant',
            field=models.FloatField(),
        ),
    ]
