# Generated by Django 4.1.7 on 2023-09-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_certificatnaissance_numero_cert_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificatnaissance',
            unique_together={('nom_enfant', 'post_nom_enfant', 'prenom_enfant')},
        ),
    ]
