# Generated by Django 4.1.7 on 2023-09-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_hopital_nom_bour_hopital_numeros_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hopital',
            options={'verbose_name': 'Hopital', 'verbose_name_plural': 'Hopitaux'},
        ),
    ]
