# Generated by Django 4.2.5 on 2023-10-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_certificat_desc_cause_desc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificatnaissance',
            unique_together={('nom_enfant', 'post_nom_enfant', 'prenom_enfant', 'date_nais_enfant')},
        ),
    ]
