# Generated by Django 4.1.7 on 2023-09-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_certificatnaissance_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actenaiss',
            options={'verbose_name': 'Acte  de Naissance', 'verbose_name_plural': 'Actes de Naissance'},
        ),
        migrations.AlterField(
            model_name='actenaiss',
            name='nom_declarant',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
