# Generated by Django 4.2.5 on 2023-10-13 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_certificatnaissance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat_desc',
            name='date_deliv_cert',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
