# Generated by Django 4.1.7 on 2023-09-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_actenaiss_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatnaissance',
            name='numero_cert',
        ),
    ]
