# Generated by Django 4.2.5 on 2023-10-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_certificatnaissance_cod_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatnaissance',
            name='cod_qr',
            field=models.ImageField(blank=True, null=True, upload_to='certificat_naissance'),
        ),
        migrations.AlterField(
            model_name='certificatnaissance',
            name='url_qrcode',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
