# Generated by Django 4.1.7 on 2023-09-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_certificatnaissance_numero_cert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actenaiss',
            old_name='qualie_declarant',
            new_name='qualite_declarant',
        ),
    ]
