# Generated by Django 4.2.5 on 2023-10-29 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_certificatnaissance_cod_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat_desc',
            name='date_desc',
            field=models.DateField(default='1959-08-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificat_desc',
            name='date_naissance_defunt',
            field=models.DateField(default='1959-08-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificat_desc',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='certificat_desc',
            name='profession_defunt',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='certificat_desc',
            name='url_qrcode',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='actenaiss',
            name='numeros_volume',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='certificatnaissance',
            unique_together={('nom_enfant', 'post_nom_enfant', 'prenom_enfant', 'sexe_enfant', 'date_nais_enfant')},
        ),
        migrations.CreateModel(
            name='ActeDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros_volume', models.CharField(blank=True, max_length=15)),
                ('nom_declarant', models.CharField(blank=True, max_length=120)),
                ('qualite_declarant', models.CharField(blank=True, max_length=20)),
                ('profession_declarant', models.CharField(blank=True, max_length=20)),
                ('residence_principale', models.CharField(blank=True, max_length=220)),
                ('residence_temporaire', models.CharField(blank=True, default=None, max_length=220, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=40)),
                ('etat_civile', models.CharField(blank=True, choices=[('m', 'Marié'), ('c', 'Celibataire')], max_length=1)),
                ('conjoint_identite', models.CharField(blank=True, max_length=120, null=True)),
                ('nom_complet_pere', models.CharField(blank=True, max_length=120)),
                ('nom_complet_mere', models.CharField(blank=True, max_length=120)),
                ('date_enregistrement', models.DateField(auto_now_add=True)),
                ('langue_redaction', models.CharField(blank=True, max_length=20)),
                ('url_qrcode', models.CharField(blank=True, max_length=2000, null=True)),
                ('cod_qr', models.ImageField(blank=True, null=True, upload_to='acte_naissance')),
                ('cert_desc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.certificat_desc')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.commune')),
            ],
            options={
                'verbose_name': 'Acte  de Descès',
                'verbose_name_plural': 'Actes de Descès',
            },
        ),
    ]
