# Generated by Django 4.2.5 on 2023-10-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_actenaiss_cod_qr_actenaiss_url_qrcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actenaiss',
            name='cod_qr',
            field=models.ImageField(blank=True, null=True, upload_to='acte_naissance'),
        ),
        migrations.AddField(
            model_name='actenaiss',
            name='url_qrcode',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='certificat_desc',
            name='cod_qr',
            field=models.ImageField(blank=True, null=True, upload_to='certificat_desces'),
        ),
    ]
